--- #YAML:1.0
name:               C-DynaLib
version:            0.59
abstract:           Dynamic Perl interface to C compiled code.
author:
    - John Tobey <John.Tobey@gmail.com>, Reini Urban <rurban@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Convert::Binary::C:  0.7
    Test:                0
    Test::More:          0
    Test::Simple:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
