--- #YAML:1.0
name:                C-DynaLib
version:             0.58
abstract:            Dynamic Perl interface to C compiled code.
license:             ~
author:              
    - John Tobey <jtobey@john-edwin-tobey.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test:                          0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
